### ISSUE TITLE
Setting name/page title via `dash(name)`

### ISSUE THREAD

**Issue by mbauman** [plotly/Dash.jl#76]
Although documented, the `dash(...)` function doesn't support having a positional string to set its name/page title.

```
help?> dash
  dash(name::String;
...
```

**Comment by waralex** [comment]
@mbauman 
This is a documentation error, I'll fix it. The page title can be set via `app.title = "my title"`, just like in the Python version. 
The `name` parameter in the Python api is a name that defines a unique name for the `flask` server and is only used for passing to flask. That's why it was removed from the api in Julia
