### ISSUE TITLE
shapes key not supported?

### ISSUE THREAD

**Issue by caseykneale** [plotly/Dash.jl#89]
Hey all, trying to stand up a dash at work for a demo - trying to show off julia. So far I love the package, few gripes beyond "give more examples please!".

Anyway I was trying to add vertical and horizontal lines to a plot, and it doesn't seem supported. Not sure if that's a plotlyjs issue or a dash issue but this is pretty important. If I'm wrong and this is supported please provide some idea of how to do it. I tried adding Dict's, NamedTuples, etc to the Layout constructor without luck...

**Comment by jackparmer** [comment]
This should work? 
http://juliaplots.org/PlotlyJS.jl/stable/examples/shapes/
Can you please share your code?

**Comment by caseykneale** [comment]
What I ended up doing was using the Plots backend instead. The key in normal Plotly to make Shapes was functional at the time I made this post - maybe it is now. I don't have the code anymore this was months ago when this was relevant to me, sorry. Feel free to close the issue, but I would recommend making an example.

**Comment by sglyon** [comment]
Thanks for opening the issue here -- sorry for the delayed response @caseykneale

@jackparmer  has the same idea as me!

When you use PlotlyJS.jl you can pass the output of `plot` directly to the `figure` property  of `dcc_graph`

That combined with the helper `vlines` and `hlines` functions provided by PlotlyJS.jl should get you on the right track

I hope all worked out with you demos and usage of Dash.jl at work!
